FROM node

WORKDIR /app
COPY package.json yarn.lock ./
COPY app/package.json ./app/package.json
COPY packages/file-graph/package.json ./packages/file-graph/package.json
COPY packages/utils/package.json ./packages/utils/package.json
RUN yarn install --frozen-lockfile

WORKDIR /app/app
CMD [ "yarn", "dev:docker", "--host", "0.0.0.0" ]