FROM node

WORKDIR /app
COPY server/package.json yarn.lock ./
RUN yarn install --frozen-lockfile

ARG DOCKER_GID=140

RUN groupadd -g $DOCKER_GID docker && usermod -aG docker node

USER node

ENV NODE_ENV=development
ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000

CMD [ "yarn", "dev" ]
