/* import the fontawesome core */
import { library } from '@fortawesome/fontawesome-svg-core'

/* import specific icons */
import {
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowRotateLeft,
  faBars,
  faBug,
  faCircleExclamation,
  faEnvelope,
  faExpand,
  faFileInvoice,
  faGear,
  faList,
  faMap,
  faPlay,
  faTerminal,
  faTriangleExclamation,
  faTrophy,
  faChevronDown,
  faTerminal,
  faTriangleExclamation,
  faTrophy,
} from '@fortawesome/free-solid-svg-icons'
import {
  faCircleQuestion,
  faCircleRight,
  faFile,
  faFolder,
  faLightbulb,
  faFile,
  faFolder,
  faLightbulb,
} from '@fortawesome/free-regular-svg-icons'
import {
  faFacebook,
  faGithub,
  faGoogle,
} from '@fortawesome/free-brands-svg-icons'

/* add icons to the library */
library.add(
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowRotateLeft,
  faBars,
  faBug,
  faCircleExclamation,
  faEnvelope,
  faExpand,
  faFileInvoice,
  faGear,
  faList,
  faCircleExclamation,
  faEnvelope,
  faExpand,
  faFileInvoice,
  faGear,
  faList,
  faMap,
  faPlay,
  faTerminal,
  faTriangleExclamation,
  faPlay,
  faTerminal,
  faTriangleExclamation,
  faTrophy,
  faCircleQuestion,
  faCircleRight,
  faFile,
  faFolder,
  faLightbulb,
  faFacebook,
  faGithub,
  faGoogle,
  faEnvelope,
  faPlay,
  faChevronDown,
  faChevronDown
)
